"""Criar tabelas de tamanho

Revision ID: a9b33494c2e6
Revises: f4850dc4bdcf
Create Date: 2026-08-11 13:44:20.848941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b33494c2e6'
down_revision: Union[str, Sequence[str], None] = 'f4850dc4bdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_tamanhos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.String(length=10), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_tamanhos_id'), 'produto_tamanhos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_tamanhos_id'), table_name='produto_tamanhos')
    op.drop_table('produto_tamanhos')
    # ### end Alembic commands ###
